### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by k1vrA** [layerhq/Atlas-Messenger-iOS#172]
Hello guys! I have some troubles with auth.

At this point

```
        NSLog(@"Registering user");
        [self.applicationController.APIManager registerUserWithName:name nonce:nonce completion:^(NSString *identityToken, NSError *error) {
            NSLog(@"User registerd and got identity token: %@", identityToken);
            if (error) {
                ATLMAlertWithError(error);
                return;
            }
```

I have this response in registerUserWithName method

```

<NSHTTPURLResponse: 0x7fc811b00f40> { URL: https://layer-identity-provider.herokuapp.com/apps/97C86162-BE4B-11E4-9959-121E260019CD/atlas_identities } { status code: 422, headers {
    Connection = "keep-alive";
    "Content-Length" = 1334;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Sat, 28 Feb 2015 00:17:47 GMT";
    Server = Cowboy;
    Status = "422 Unprocessable Entity";
    Via = "1.1 vegur";
    "X-Request-Id" = "6ed33e94-fd02-4106-ae1c-696319affab3";
    "X-Runtime" = "0.012798";
} }

```

After this response i see this warning :(

![screen shot 2015-02-28 at 3 29 23 am](https://cloud.githubusercontent.com/assets/5331145/6423632/088a1d06-befa-11e4-8909-d7767c693ff1.png)

**Comment by rbaulin** [comment]
The sample seems to be a little bit outdated. Replace `registerUserWithName:` from `ATLMAPIManager.m` class with the following: 


    - (void)registerUserWithName:(NSString*)userID nonce:(NSString *)nonce completion:(void (^)(NSString *identityToken, NSError *error))completion
    {
        NSParameterAssert(userID);
        NSParameterAssert(nonce);
        NSParameterAssert(completion);
        
        NSString *appID = YOUR_LAYER_APP_ID;
        
        NSURL *identityTokenURL = [NSURL URLWithString:@"https://layer-identity-provider.herokuapp.com/identity_tokens"];
        NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:identityTokenURL];
        request.HTTPMethod = @"POST";
        [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
        [request setValue:@"application/json" forHTTPHeaderField:@"Accept"];
        
        NSDictionary *parameters = @{ @"app_id": appID, @"user_id": userID, @"nonce": nonce };
        NSData *requestBody = [NSJSONSerialization dataWithJSONObject:parameters options:0 error:nil];
        request.HTTPBody = requestBody;
        
        NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
        NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfiguration];
        [[session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            if (error) {
                completion(nil, error);
                return;
            }
            
            // Deserialize the response
            NSDictionary *responseObject = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
            if(![responseObject valueForKey:@"error"])
            {
                NSString *identityToken = responseObject[@"identity_token"];
                completion(identityToken, nil);
            }
            else
            {
                NSString *domain = @"layer-identity-provider.herokuapp.com";
                NSInteger code = [responseObject[@"status"] integerValue];
                NSDictionary *userInfo =
                @{
                  NSLocalizedDescriptionKey: @"Layer Identity Provider Returned an Error.",
                  NSLocalizedRecoverySuggestionErrorKey: @"There may be a problem with your APPID."
                  };
                
                NSError *error = [[NSError alloc] initWithDomain:domain code:code userInfo:userInfo];
                completion(nil, error);
            }
            
        }] resume];
    }

Should pass the authorization step now.

**Comment by kcoleman731** [comment]
Hi @k1vrA! Thank you very much for your email. It looks like you are not configuring the `NSURLSession` properly. If you look in the ATLMAPIManager class, you will see that we configure the `urlSession` via the following method. 

```- (NSURLSession *)defaultURLSession
{
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
    configuration.HTTPAdditionalHeaders = @{@"Accept": @"application/json", @"Content-Type": @"application/json", @"X_LAYER_APP_ID": self.layerClient.appID.UUIDString};
    return [NSURLSession sessionWithConfiguration:configuration];
}```

If you get that setup, you should be good to go.
