### ISSUE TITLE
Atlas messenger crashing when register with new user

### ISSUE THREAD

**Issue by gopaldevra** [layerhq/Atlas-Messenger-iOS#195]
Hello,

I am having problem with the registration with atlas messenger but sometimes it's crashing when i log in too with my user name.

And I'm having these debug descriptions are as
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1].
and
error = "Unprocessable Entity";
    status = 422

Please let me know where I'm making mistake.

**Comment by kmahal** [comment]
HI @gopaldevra please paste the call stack. When exactly is this issue happening?  What step of authentication?

**Comment by rishi-lambe** [comment]
User registered and got identity token: (null) (error=Error Domain=com.layer.Atlas-Messenger Code=2 "Unprocessable Entity" UserInfo={NSLocalizedDescription=Unprocessable Entity, responseBody={"status":"422","error":"Unprocessable Entity"}})
