### ISSUE TITLE
Date from last message overlaps new message

### ISSUE THREAD

**Issue by andrey-pervushin-appus** [layerhq/Atlas-Messenger-iOS#201]
See gray date on blue bubble

![2015-09-25 12 47 01](https://cloud.githubusercontent.com/assets/11504112/10070374/afb0e344-62ba-11e5-9dd3-ba4f1fe1ffab.png)

**Comment by andrey-pervushin-appus** [comment]
any info about that?

**Comment by kmahal** [comment]
@andrey-pervushin-appus are you still seeing this issue?  On atlas messenger?

**Comment by JRam13** [comment]
I opened a ticket on the Atlas github about this, which has gone mostly ignored. I have a solution there. 

https://github.com/layerhq/Atlas-iOS/issues/1067

**Comment by feifanzhou** [comment]
Continuing conversation [in Atlas repo](https://github.com/layerhq/Atlas-iOS/issues/1067)
