### ISSUE TITLE
EXC_BAD_ACCESS when reopening chat after exiting with keyboard open

### ISSUE THREAD

**Issue by mtford90** [layerhq/Atlas-Messenger-iOS#204]
This only happens if I leave the conversation with the keyboard open and then try to reopen the same chat. As soon as you tap the conversation - boom, bad access.

I've attached a GIF demonstrating the issue on iOS 9

![crash](https://cloud.githubusercontent.com/assets/1734057/10225931/ed7c09fe-685c-11e5-8bf2-66497cfbd9ce.gif)

**Comment by kmahal** [comment]
@mtford90 got a forthcoming fix for the crash: https://github.com/layerhq/Atlas-Messenger-iOS/pull/205

**Comment by mtford90** [comment]
@kmahal awesome!
