### ISSUE TITLE
Swift implementation example

### ISSUE THREAD

**Issue by sibeliusseraphini** [layerhq/Atlas-Messenger-iOS#210]
Is there a Swift implementation of Atlas-Messenger-IOS or how to use Atlas-IOS in Swift?

**Comment by kmahal** [comment]
@sibeliusseraphini currently nothing official from Layer, but there is this: https://github.com/kwkhaw/Layer-Parse-iOS-Swift-Example which should help explain a lot.  The APIs are the same, the syntax is all that differs.
