### ISSUE TITLE
When I trying to login in to Atlas Messenger ios App - App get crashed

### ISSUE THREAD

**Issue by rishi-lambe** [layerhq/Atlas-Messenger-iOS#211]
I got the following error on console:
 User registered and got identity token: (null) (error=Error Domain=com.layer.Atlas-Messenger Code=2 "Unprocessable Entity" UserInfo={NSLocalizedDescription=Unprocessable Entity, responseBody={"status":"422","error":"Unprocessable Entity"}})

**Comment by LukeDurrant** [comment]
Also getting this as well

**Comment by LukeDurrant** [comment]
@rishi-lambe did you find a solution?

**Comment by LukeDurrant** [comment]
https://github.com/layerhq/Atlas-Messenger-iOS/pull/218 fixes this

**Comment by kmahal** [comment]
I'll close this if it's tracked there.  Thank you.
