### ISSUE TITLE
How to send a voice message ?

### ISSUE THREAD

**Issue by rishi-lambe** [layerhq/Atlas-Messenger-iOS#212]
I want to send a voice message to other user. How to send ?

**Comment by kmahal** [comment]
@rishi-lambe read over `LayerKit`'s documentation on how to send data objects.  This is not an Atlas implementation issue, so I'll be closing out this ticket.  Look at how images are sent via Atlas to get a better idea on this.

**Comment by rishi-lambe** [comment]
Thanks . Sound implmentation done
