### ISSUE TITLE
Sender is not showing on some devices

### ISSUE THREAD

**Issue by jessearmand** [layerhq/Atlas-Messenger-iOS#215]
I have noticed that sender name is not showing on an iPad mini 2 with iOS 9.2 but it's fine on iPhone 6S with iOS 9.2. What could be the difference?

![image](https://cloud.githubusercontent.com/assets/67312/12256077/7722c5e8-b935-11e5-8ef3-30dc21f6a827.png)

**Comment by kmahal** [comment]
@jessearmand that occurs if our user management class hasn't downloaded new users that your other devices may have.  If you sign out/sign back in everything should work.
