### ISSUE TITLE
"Unprocessable Entity" error while registering user

### ISSUE THREAD

**Issue by cowbjt** [layerhq/Atlas-Messenger-iOS#227]
Hi guys,

This is the error message:
User registered and got identity token: (null) (error=Error Domain=com.layer.Atlas-Messenger Code=2 "Unprocessable Entity" UserInfo={NSLocalizedDescription=Unprocessable Entity, responseBody={"status":"422","error":"Unprocessable Entity"}})

ATLMLayerAppID is set, Layer Client is Connected, Authentication Nonce from layer is also got.

Looks like #218, but I've pulled and updated.
Did I miss any thing?

**Comment by santiagofm** [comment]
+1

**Comment by feifanzhou** [comment]
It's not the best error, but that could happen if you've registered more than 25 IDs while playing around with this. This app is designed to be a demo; one of the demo limitations is that you can't have more than 25 registered users. For a production app, you'll want to setup your own identity provider that can support the [authentication flow](https://developer.layer.com/docs/ios/guides#authentication).
