### ISSUE TITLE
Build fail: ATLMParticipantDataSource.m is missing

### ISSUE THREAD

**Issue by rrodrigu3z** [layerhq/Atlas-Messenger-iOS#230]
Hi! I was trying to build the demo, but I get this error:

clang: error: no such file or directory: '/Users/rrodriguez/Documents/Proyectos/layer_api/atlas/Atlas-Messenger-iOS/Code/Utilities/ATLMParticipantDataSource.m'
clang: error: no input files

I can see that ATLMParticipantDataSource was removed in af3608ce9a21f10af805f9c19ce0b2cb5ac33f86 

Any ideas? 
Thanks!

**Comment by bertoBertito** [comment]
Hi, same issue here. 

clang: error: no such file or directory: '/Users/myFolder/Documents/Atlas-Messenger-iOS/Code/Utilities/ATLMParticipantDataSource.m'
clang: error: no input files


Any ideas?
Thanks

**Comment by santiagofm** [comment]
In xcode's project navigator goto Code/Utilities & remove ATLMParticipantDataSource.h ATLMParticipantDataSource.m from the project.
Still can't get the app to work correctly because of #227 though

**Comment by rrodrigu3z** [comment]
Hey! Thanks.. It's working now!

I'm not an iOS developer, so, thanks!

About #227 I'm not getting that error, looks like everything it's working.
