### ISSUE TITLE
NSInvalidArgumentException', reason: '-[LYRObjectContext mergeChanges:]:

### ISSUE THREAD

**Issue by AlbertoLourenco** [layerhq/Atlas-Messenger-iOS#231]
Please, help me.

**Comment by daniel-maness** [comment]
@AlbertoLourenco can you provide more context around this?

1. What versions of LayerKit, Atlas, and Atlas Messenger are you using?
2. Is this reproducible and, if so, what are the steps?

**Comment by AlbertoLourenco** [comment]
Sorry, I can't remember. And I'm not working with it now, so this issues was closed. Tks. :)
