### ISSUE TITLE
[PodLayerKit_LYRIError message] crash

### ISSUE THREAD

**Issue by adina-abduraman** [layerhq/Atlas-Messenger-iOS#234]
Hi guys, 

I am working with Layer and Atlas ios. From time to time, as soon as I launch the app, it crashes with the following crash report:

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PodLayerKit_LYRIError message]: unrecognized selector sent to instance 0x7f9a3ce0'

Any ideas in this?
Thanks

**Comment by vkostechko** [comment]
any news?

**Comment by feifanzhou** [comment]
This has been resolved since LayerKit 0.22.0.
