### ISSUE TITLE
Errors building the project

### ISSUE THREAD

**Issue by charlsagente** [layerhq/Atlas-Messenger-iOS#242]
Hi, my name is Carlos. I have followed the readme to build the project but i get too many errors. Could you help me please?. I´m using Osx 10.11.6, Ruby 2.1.2p95, cocoapods 0.39.0, 
![image](https://cloud.githubusercontent.com/assets/948024/17630942/6c6eb518-6087-11e6-8874-f392631e43c6.png)

**Comment by pramodsharma403** [comment]
same issue with me

**Comment by JoeFerrucci** [comment]
Any solutions yet?

**Comment by JoeFerrucci** [comment]
@charlsagente  @pramodsharma403 
Do `pod install` with Cocoapods 1.0.x
