### ISSUE TITLE
documentation code typo

### ISSUE THREAD

**Issue by kenzanboo** [layerhq/Atlas-Messenger-iOS#257]
running this: rake configure:set["appID", "{YOUR_APP_ID}"]

results in this:

rake aborted!
Don't know how to build task 'configure:set[appID,' (see --tasks)
/Users/username/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

The problem is that there is a space between  ...appID",SPACE_HERE"{YOUR...
Please remove the space in the docs so that future people who copy paste that code this will not run into the same rake aborted issue.

**Comment by daniel-maness** [comment]
Fixed with this PR: https://github.com/layerhq/Atlas-Messenger-iOS/pull/260
