### ISSUE TITLE
identity_provider_url is null

### ISSUE THREAD

**Issue by billychasen** [layerhq/Atlas-Messenger-iOS#261]
App is crashing on start because identity_provider_url is null in LayerConfiguration.json

What should it be set to for this demo? And "name" as well?

Thanks

**Comment by daniel-maness** [comment]
@billychasen That should be set to the URL you're using for your identity provider that generates your identity token. If you're using our Instastart product, it would look something like `"https://<your-app-name>.herokuapp.com/authenticate"`
